# Generated by Django 5.1.1 on 2024-09-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Feriado')),
                ('dia', models.IntegerField(verbose_name='dia')),
                ('mes', models.IntegerField(verbose_name='mes')),
            ],
        ),
    ]
